baseURL = "http://localhost"
languageCode = 'zh-Hans'
theme = "dream"
title = "Bestzy's Blog"
defaultContentLanguage = "zh"
hasCJKLanguage = true

[params]
favicon = "favicon.ico"
showTableOfContents = true
showSummaryCoverInPost = true
lightTheme = "emerald"
darkTheme = "forest"
author = "bestzy"
description = "bestzyçš„ä¸ªäººåšå®¢ï½"
headerTitle = "Bestzy"
motto = "ğŸš€å…ˆè¡Œå…¶äº‹ï¼Œåè‡»å…¶å–„ï¼Œå†æ±‚å…¶ä¼˜ï¼"
rss = true
email = "805043989@qq.com"
avatar = "https://avatars.githubusercontent.com/u/43753176?v=4"
reorderShares = ["x", "facebook"]
stickyNav = true
reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
[params.experimental]
jsDate = true
jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"